## 예외 처리

```python
try:
    ...
except [발생 오류[as 오류 메시지 변수]]:	# except: 이 경우는 오류 종류 상관없이 except블록 수행
    ...							# except 발생 오류: 오류 이름과 일치할 때만 except블록 수행
```

```python
try:
    4 / 0
except ZeroDivisionError as e:
    print(e)
```

> 결과 값 : division by zero 4를 0으로 나누려해서 나는 오류를 오류 메시지 변수(e)에 담아 결과를 출력했다.

```python
f = open('foo.txt', 'w')
try:
    # 무언가를 수행한다.
finally:
    f.close()
```

> finally 절은 예외 발생 여부와 상관없이 항상 실행된다. 보통 finally절은 위 처럼 사용한 리소스를 close해야 할 때에 많이 쓰인다.

```python
try:
    a = [1,2]
    print(a[3])
    4/0
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다.")
except IndexError:		# 인덱싱 오류가 먼저 발생하므로 이 부분만 실행됨.
    print("인덱싱 할 수 없습니다.")		# pass라고 쓴다면 오류를 그냥 통과함.
0으로 나눌 수 없습니다.
```

> 여러 개의 오류를 처리할 때 쓰는 방법.

```python
try:
	a = [1, 2]
	print(a[3])
	4 / 0
except (ZeroDivisionError, IndexError) as e:
	print(e)
```

> 2개 이상의 오류를 동시에 처리할 때 사용하는 방법. 괄호를 사용하여 함께 묶어 처리하면 된다.

```python
class Bird:
	def fly(self):
		raise NotImplementedError
```

> NotImplementedError는 꼭 작성해야 하는 부분이 구현되지 않았을 경우 일부러 오류를 일으키키 위해 사용한다.

```python
class Eagle(Bird):
	pass

eagle = Eagle()
eagle.fly()
```

> 오류가 발생할 것이다. 오류가 발생하지 않으려면 Eagle클래스에 fly()함수를 반드시 구현해야 한다.

```python
class Eagle(Bird):
	def fly(self):
		print("very fast")
		
eagle = Eagle()
eagle.fly()
# very fast
```



## 예외 만들기

```python
class MyError(Exception):
	pass
	
def say_nick(nick):
	if nick == "바보":
		raise MyError()
	print(nick)
	
say_nick("천사")
say_nick("바보")

##################################
천사
Traceback (most recent call last):
  File "...", line 11, in <module>
    say_nick("바보")
  File "...", line 7, in say_nick
    raise MyError()
__main__.MyError
```

```
try:
    say_nick("천사")
    say_nick("바보")
except MyError:
    print("허용되지 않는 별명입니다.")
#######################################
천사
허용되지 않는 별명입니다.
```

```python
class MyError(Exception):
	def __str__(self):	# 오류 시 메시지를 출력하는 메서드!!!
		return "허용되지 않는 별명입니다."
try:
	say__nick("천사")
	say__nick("바보")
except MyError as e:
	print(e)
################################
천사
허용되지 않는 별명입니다.
```

> str메서드를 사용하지 않으면 오류 메시지가 출력이 되지 않는다. 오류 클래스에 str메서드를 명시해야 한다는 점 잊지 말자. str메서드는 print(e)처럼 오류 메시지를 출력할 경우에 호출되는 메서드이다.